Add loadbalancer

diff --git a/swarm-mode/manager.yaml b/swarm-mode/manager.yaml
--- a/swarm-mode/manager.yaml
+++ b/swarm-mode/manager.yaml
@@ -76,8 +76,91 @@ Conditions:
   HasIAMUserSSHAccess: !Equals [!Ref IAMUserSSHAccess, 'true']
   HasSSHBastionSecurityGroup: !Not [!Equals [!Ref ParentSSHBastionStack, '']]
   UsePreRelease: !Equals [!Ref DockerPreRelease, 'true']
+  HasSwarmJoinToken: !Not [!Equals [!Ref SwarmManagerJoinToken, '']]
 
 Resources:
+
+  SecurityGroup:
+    Type: AWS::EC2::SecurityGroup		
+    Properties:
+      GroupDescription: Allow http to client host
+      VpcId:
+        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
+      SecurityGroupIngress:
+      - IpProtocol: tcp		
+        FromPort: '80'
+        ToPort: '80'
+        CidrIp: 0.0.0.0/0
+      - IpProtocol: tcp
+        FromPort: '8080'
+        ToPort: '8080'
+        CidrIp: 0.0.0.0/0
+
+  LoadBalancer:
+    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
+    Properties:
+      Scheme: internet-facing
+      Subnets:
+      - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPublic'
+      - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPublic'
+      - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetCPublic'
+      SecurityGroups:
+      - !Ref SecurityGroup
+
+  Listener80:
+    Type: AWS::ElasticLoadBalancingV2::Listener
+    Properties:
+      DefaultActions:
+      - Type: forward		
+        TargetGroupArn: !Ref TargetGroup80
+      LoadBalancerArn: !Ref LoadBalancer
+      Port: '80'
+      Protocol: HTTP
+
+  TargetGroup80:
+    Type: AWS::ElasticLoadBalancingV2::TargetGroup
+    Properties:
+      HealthCheckIntervalSeconds: 5
+      HealthCheckProtocol: HTTP
+      HealthCheckTimeoutSeconds: 3
+      HealthCheckPath: "/"
+      HealthyThresholdCount: 4
+      Matcher:
+        HttpCode: '200'
+      Port: 80
+      Protocol: HTTP
+      Targets: []
+      UnhealthyThresholdCount: 3
+      VpcId:
+        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
+
+  Listener8080:
+    Type: AWS::ElasticLoadBalancingV2::Listener
+    Properties:
+      DefaultActions:
+      - Type: forward
+        TargetGroupArn: !Ref TargetGroup8080
+      LoadBalancerArn: !Ref LoadBalancer
+      Port: '8080'
+      Protocol: HTTP
+
+  TargetGroup8080:
+    Type: AWS::ElasticLoadBalancingV2::TargetGroup
+    Properties:
+      HealthCheckIntervalSeconds: 5
+      HealthCheckProtocol: HTTP
+      HealthCheckTimeoutSeconds: 3
+      HealthCheckPath: "/"
+      HealthyThresholdCount: 4
+      Matcher:
+        HttpCode: '200'
+      Port: 8080
+      Protocol: HTTP
+      Targets: []
+      UnhealthyThresholdCount: 3
+      VpcId:
+        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
+
 
   SwarmSecurityGroup:
     Type: AWS::EC2::SecurityGroup
@@ -214,6 +297,7 @@ Resources:
       MinSize: !Ref DesiredInstances
       MaxSize: 7
       DesiredCapacity: !Ref DesiredInstances
+      TargetGroupARNs: [!Ref TargetGroup80, !Ref TargetGroup8080]
       MetricsCollection:
       - Granularity: 1Minute
         Metrics:
@@ -241,7 +325,11 @@ Resources:
       AWS::CloudFormation::Init:
         configSets:
           default:
-            !If [HasIAMUserSSHAccess, [ssh-access, docker-ubuntu, swarm], [docker-ubuntu, swarm]]
+            !If
+            - HasSwarmJoinToken
+            - !If [HasIAMUserSSHAccess, [ssh-access, docker-ubuntu, swarm-join], [docker-ubuntu, swarm-join]]
+            - !If [HasIAMUserSSHAccess, [ssh-access, docker-ubuntu, swarm-init], [docker-ubuntu, swarm-init]]
+
         ssh-access:
           files:
             '/opt/authorized_keys_command.sh':
@@ -327,39 +415,39 @@ Resources:
               command: 'sudo docker run hello-world'
             'i_verify_installation':
               command: 'docker run hello-world'
-        swarm:
+        swarm-init:
           commands:
-
             'a_join_swarm':
-              command: !Sub | 
-                if [ "${SwarmManagerJoinToken}" == "" ] ; then
-                  docker swarm init
-                else
-                  INSTANCE_ID="`wget -q -O - http://instance-data/latest/meta-data/instance-id`"
-                  AG_NAME=$(aws autoscaling describe-auto-scaling-instances --instance-ids $INSTANCE_ID --region eu-west-1 --query AutoScalingInstances[].AutoScalingGroupName --output text)
-
-                  for ID in $(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $AG_NAME --region eu-west-1 --query AutoScalingGroups[].Instances[].InstanceId --output text);
-                  do
-                    # Ignore "myself"
-                    if [ "$ID" == "$INSTANCE_ID" ] ; then
-                        continue;
-                    fi
-
-                    IP=$(aws ec2 describe-instances --instance-ids $ID --region eu-west-1 --query Reservations[].Instances[].PrivateIpAddress --output text)
-                    if [ ! -z "$IP" ] ; then
-                      echo "Try to join swarm with IP $IP"
-
-                      # Join the swarm; if it fails try the next one
-                      docker swarm join --token ${SwarmManagerJoinToken} $IP:2377 && break || continue
-                    fi
-                  done
-                fi
+              command: 'docker swarm init'
 
             'b_swarm_healthcheck':
-              command: !Sub |
-                if [ ! -z "${SwarmManagerJoinToken}" ] ; then
-                  docker node ls
-                fi
+              command: 'docker node ls'
+
+        swarm-join:
+          commands:
+            'a_join_swarm':
+              command: !Sub | 
+                INSTANCE_ID="`wget -q -O - http://instance-data/latest/meta-data/instance-id`"
+                ASG_NAME=$(aws autoscaling describe-auto-scaling-instances --instance-ids $INSTANCE_ID --region eu-west-1 --query AutoScalingInstances[].AutoScalingGroupName --output text)
+
+                for ID in $(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --region eu-west-1 --query AutoScalingGroups[].Instances[].InstanceId --output text);
+                do
+                  # Ignore "myself"
+                  if [ "$ID" == "$INSTANCE_ID" ] ; then
+                      continue;
+                  fi
+
+                  IP=$(aws ec2 describe-instances --instance-ids $ID --region eu-west-1 --query Reservations[].Instances[].PrivateIpAddress --output text)
+                  if [ ! -z "$IP" ] ; then
+                    echo "Try to join swarm with IP $IP"
+
+                    # Join the swarm; if it fails try the next one
+                    docker swarm join --token ${SwarmManagerJoinToken} $IP:2377 && break || continue
+                  fi
+                done
+
+            'b_swarm_healthcheck':
+              command: 'docker node ls'
 
 
     Properties:
@@ -367,6 +455,7 @@ Resources:
       InstanceType: !Ref InstanceType
       SecurityGroups:
       - !Ref SwarmSecurityGroup
+      - !Ref SecurityGroup
 
       IamInstanceProfile: !Ref InstanceProfile
       KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
@@ -388,7 +477,8 @@ Resources:
           easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
           ln -s /root/aws-cfn-bootstrap-latest/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
 
-          echo "20"
+          # TODO: Replace by build-number. Needed to trigger ASG update process.
+          echo "1"
 
           cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource SwarmManagerLaunchConfiguration 
           cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource SwarmManagerAutoScalingGroup
@@ -404,3 +494,7 @@ Outputs:
     Value: !Ref SwarmManagerAutoScalingGroup
     Export:
       Name: !Sub '${AWS::StackName}-SwarmManagerAutoScalingGroup'
+  ServiceUrl:
+    Description: URL of the load balancer for the sample service.
+    Value: !Sub http://${LoadBalancer.DNSName}
+
